Repository fkie-cad/Logprep, pull requests merged in 2022-05, with the labels that each got.

#78 Fix typo in processor_stats.py
  logprep/processor/base/processor.py
  logprep/util/processor_stats.py
  tests/unit/processor/base.py
  tests/unit/util/test_processor_stats.py
Labels: bug

#86 Add python 3.7 to 3.9 support
  .github/workflows/ci.yml
  .github/workflows/main.yml
  README.md
  requirements.in
  requirements.txt
  requirements_dev.txt
  tox.ini
Labels: documentation, enhancement

#87 Fix quickstart config and add regression tests
  logprep/run_logprep.py
  quickstart/exampledata/config/pipeline.yml
  quickstart/exampledata/rules/labeler/generic/example_rule.yml
  quickstart/exampledata/rules/labeler/specific/example_rule.yml
  quickstart/exampledata/rules/pre_detector/generic/example_rule.yml
  quickstart/exampledata/rules/pre_detector/specific/example_rule.yml
  tests/unit/test_run_logprep.py
Labels: bug, enhancement

#88 Revert "Fix quickstart config and add regression tests"
  logprep/run_logprep.py
  quickstart/exampledata/config/pipeline.yml
  quickstart/exampledata/rules/labeler/rules/example_rule.yml
  quickstart/exampledata/rules/labeler/specific/example_rule.yml
  quickstart/exampledata/rules/pre_detector/rules/example_rule.yml
  quickstart/exampledata/rules/pre_detector/specific/example_rule.yml
  tests/unit/test_run_logprep.py
Labels: bug, enhancement

#89 Fix quickstart config and add regression tests
  logprep/processor/base/rule.py
  logprep/run_logprep.py
  quickstart/exampledata/config/pipeline.yml
  quickstart/exampledata/rules/labeler/generic/example_rule.yml
  quickstart/exampledata/rules/labeler/specific/example_rule.yml
  quickstart/exampledata/rules/pre_detector/generic/example_rule.yml
  quickstart/exampledata/rules/pre_detector/specific/example_rule.yml
  tests/unit/test_run_logprep.py
Labels: bug, enhancement

#80 Add semgrep
  .github/workflows/ci.yml
  .github/workflows/main.yml
  .semgrep_rules/logprep_specific/processor-rules.yml
  README.md
  tox.ini
Labels: enhancement

#91 Refactor Prometheus Metrics
  doc/source/user_manual/configuration/logprep.rst
  logprep/framework/pipeline.py
  logprep/framework/pipeline_manager.py
  logprep/run_logprep.py
  logprep/runner.py
  logprep/util/processor_stats.py
  logprep/util/prometheus_exporter.py
  tests/unit/framework/test_pipeline.py
  tests/unit/framework/test_pipeline_manager.py
  tests/unit/util/test_processor_stats.py
  tests/unit/util/test_prometheus_exporter.py
Labels: documentation, enhancement

#100 Add semgrep rule repository to pipeline
  .github/workflows/ci.yml
  .github/workflows/main.yml
  logprep/processor/clusterer/factory.py
Labels: enhancement
