Repository fkie-cad/Logprep, pull requests merged in 2022-07, with the labels that each got.

#66 Make template replacer write even if no target field exists
  logprep/processor/template_replacer/processor.py
  tests/unit/processor/template_replacer/test_template_replacer.py
Labels: enhancement

#136 Print logprep version via CLI
  CHANGELOG.md
  doc/source/getting_started.rst
  doc/source/index.rst
  doc/source/installation.rst
  doc/source/user_manual/configuration/index.rst
  doc/source/user_manual/configuration/logprep.rst
  logprep/metrics/metric_targets.py
  logprep/run_logprep.py
  logprep/util/prometheus_exporter.py
  quickstart/exampledata/config/pipeline.yml
  tests/unit/test_run_logprep.py
Labels: documentation, enhancement

#148 Fix metric tracking performance
  CHANGELOG.md
  logprep/framework/pipeline.py
  logprep/metrics/metric_exposer.py
  logprep/metrics/metric_targets.py
  tests/unit/metrics/test_metric_exposer.py
  tests/unit/metrics/test_metric_targets.py
Labels: bug, enhancement

#147 Fix Auto Rule Tester
  CHANGELOG.md
  logprep/processor/clusterer/processor.py
  logprep/util/auto_rule_tester.py
  tests/testdata/auto_tests/clusterer/rules/generic/rule_with_custom_tests.yml
  tests/testdata/auto_tests/clusterer/rules/specific/rule_with_custom_tests.yml
  tests/testdata/auto_tests/dropper/rules/generic/drop_field.json
  tests/testdata/auto_tests/dropper/rules/generic/drop_field_test.json
  tests/testdata/auto_tests/dropper/rules/specific/drop_field.json
  tests/testdata/auto_tests/dropper/rules/specific/drop_field_test.json
  tests/testdata/auto_tests/labeler/rules/generic/auto_test_labeling_match.json
  tests/testdata/auto_tests/labeler/rules/generic/auto_test_labeling_match_test.json
  tests/testdata/auto_tests/labeler/rules/specific/auto_test_labeling_mismatch.json
  tests/testdata/auto_tests/labeler/rules/specific/auto_test_labeling_mismatch_test.json
  tests/testdata/auto_tests/labeler/rules/specific/auto_test_labeling_no_test_.json
  tests/testdata/auto_tests/normalizer/rules/generic/auto_test_normalizer_match.json
  tests/testdata/auto_tests/normalizer/rules/generic/auto_test_normalizer_match_test.json
  tests/testdata/auto_tests/normalizer/rules/specific/auto_test_normalizer_mismatch.json
  tests/testdata/auto_tests/normalizer/rules/specific/auto_test_normalizer_mismatch_test.json
  tests/testdata/auto_tests/normalizer/rules/specific/auto_test_normalizer_no_test_.json
  tests/testdata/auto_tests/pre_detector/rules/generic/auto_test_pre_detector_match.json
  tests/testdata/auto_tests/pre_detector/rules/generic/auto_test_pre_detector_match_test.json
  tests/testdata/auto_tests/pre_detector/rules/specific/auto_test_pre_detector_mismatch.json
  tests/testdata/auto_tests/pre_detector/rules/specific/auto_test_pre_detector_mismatch_test.json
  tests/testdata/auto_tests/pre_detector/rules/specific/auto_test_pre_detector_no_test_.json
  tests/testdata/auto_tests/pseudonymizer/rules/generic/auto_test_pseudonymizer_match.json
  tests/testdata/auto_tests/pseudonymizer/rules/generic/auto_test_pseudonymizer_match_test.json
  tests/testdata/auto_tests/pseudonymizer/rules/specific/auto_test_pseudonymizer_mismatch.json
  tests/testdata/auto_tests/pseudonymizer/rules/specific/auto_test_pseudonymizer_mismatch_test.json
  tests/testdata/auto_tests/pseudonymizer/rules/specific/auto_test_pseudonymizer_no_test_.json
  tests/testdata/auto_tests/template_replacer/rules/generic/template_replacer.json
  tests/testdata/auto_tests/template_replacer/rules/generic/template_replacer_test.json
  tests/testdata/auto_tests/template_replacer/rules/specific/template_replacer.json
  tests/testdata/auto_tests/template_replacer/rules/specific/template_replacer_test.json
  tests/testdata/config/config-auto-tests.yml
  tests/testdata/unit/auto_rule_tester/normalizer/regex_mapping.yml
  tests/testdata/unit/auto_rule_tester/normalizer/rules/generic/auto_test_normalizer_match.json
  tests/testdata/unit/auto_rule_tester/normalizer/rules/generic/auto_test_normalizer_match_test.json
  tests/testdata/unit/auto_rule_tester/normalizer/rules/specific/auto_test_normalizer_match.json
  tests/testdata/unit/auto_rule_tester/normalizer/rules/specific/auto_test_normalizer_match_test.json
  tests/unit/util/test_auto_rule_tester.py
Labels: bug, enhancement
