Repository fkie-cad/Logprep, pull requests merged in 2022-06, with the labels that each got.

#120 Add checkout before fetching latest git tag
  .github/workflows/publish-release-to-pypi.yml
Labels: bug

#67 Add mysql to generic adder
  .github/workflows/ci.yml
  CHANGELOG.md
  doc/source/user_manual/configuration/processor.rst
  doc/source/user_manual/rule_language.rst
  logprep/processor/generic_adder/mysql_connector.py
  logprep/processor/generic_adder/processor.py
  logprep/processor/generic_adder/rule.py
  requirements.in
  requirements.txt
  requirements_dev.txt
  tests/testdata/unit/generic_adder/rules/generic/rules.json
  tests/unit/processor/generic_adder/test_generic_adder.py
  tests/unit/processor/generic_adder/test_generic_adder_rule.py
Labels: enhancement

#135 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation
