Repository fkie-cad/Logprep, pull requests merged in 2022-04, with the labels that each got.

#40 refactor list comparison tests to use base class
  logprep/processor/list_comparison/factory.py
  logprep/processor/list_comparison/processor.py
  logprep/processor/list_comparison/rule.py
  logprep/processor/normalizer/processor.py
  tests/testdata/unit/list_comparison/rules/generic/user_check.json
  tests/testdata/unit/list_comparison/rules/specific/user_check_specific.json
  tests/unit/processor/base.py
  tests/unit/processor/list_comparison/test_list_comparison.py
  tests/unit/processor/list_comparison/test_list_comparison_rule.py
Labels: enhancement

#43 Dev refactor generic adder tests to use base class
  logprep/processor/generic_adder/factory.py
  logprep/processor/generic_adder/processor.py
  logprep/processor/generic_adder/rule.py
  tests/testdata/unit/generic_adder/rules/generic/rules.json
  tests/testdata/unit/generic_adder/rules/specific/specific_rules.json
  tests/unit/processor/base.py
  tests/unit/processor/generic_adder/test_generic_adder.py
  tests/unit/processor/generic_adder/test_generic_adder_rule.py
Labels: enhancement

#45 dev refactor geoip_enricher to use base class
  logprep/processor/base/processor.py
  logprep/processor/geoip_enricher/factory.py
  logprep/processor/geoip_enricher/processor.py
  tests/testdata/unit/geoip_enricher/rules/generic/geoip_all.json
  tests/testdata/unit/geoip_enricher/rules/geoip_all.json
  tests/testdata/unit/geoip_enricher/rules/specific/geoip_all.json
  tests/unit/processor/base.py
  tests/unit/processor/geoip_enricher/test_geoip_enricher.py
Labels: enhancement

#46 Refactor GenericResolver to use BaseProcessorTestCase
  logprep/processor/generic_resolver/factory.py
  logprep/processor/generic_resolver/processor.py
  logprep/processor/generic_resolver/rule.py
  logprep/processor/list_comparison/processor.py
  logprep/processor/list_comparison/rule.py
  tests/testdata/unit/generic_resolver/rules/generic/rule_01.json
  tests/testdata/unit/generic_resolver/rules/specific/rule_01.json
  tests/unit/processor/generic_resolver/test_generic_resolver.py
  tests/unit/processor/generic_resolver/test_generic_resolver_rule.py
  tests/unit/processor/list_comparison/test_list_comparison.py
  tests/unit/processor/list_comparison/test_list_comparison_rule.py
Labels: enhancement

#55 dev refactor template_replacer to use base class
  logprep/processor/template_replacer/factory.py
  logprep/processor/template_replacer/processor.py
  tests/testdata/unit/template_replacer/rules/generic/template_replacer.json
  tests/testdata/unit/template_replacer/rules/specific/template_replacer.json
  tests/testdata/unit/template_replacer/rules/template_replacer.json
  tests/unit/processor/base.py
  tests/unit/processor/template_replacer/test_template_replacer.py
Labels: enhancement

#49 Dev refactor domain label extractor to use base processor test case
  logprep/processor/domain_label_extractor/factory.py
  logprep/processor/domain_label_extractor/processor.py
  logprep/processor/domain_label_extractor/rule.py
  tests/testdata/config/config.yml
  tests/testdata/unit/domain_label_extractor/rules/generic/domain_label_extractor_gen.json
  tests/testdata/unit/domain_label_extractor/rules/specific/domain_label_extractor.json
  tests/unit/processor/domain_label_extractor/test_domain_label_extractor.py
  tests/unit/processor/domain_label_extractor/test_domain_label_extractor_factory.py
  tests/unit/processor/domain_label_extractor/test_domain_label_extractor_rule.py
Labels: enhancement

#56 Revise README.md
  README.md
Labels: documentation

#57 Revise rst documentation for processor configs
  doc/source/conf.py
  doc/source/user_manual/configuration/processor.rst
Labels: documentation

#62 Remove no longer existing labeler exceptions from schema validator
  logprep/util/schema_and_rule_checker.py
  tests/unit/util/test_schema_and_rule_checker.py
Labels: bug

#77 Fix init of the generic adder rule trees
  logprep/processor/generic_adder/processor.py
Labels: bug

#76 Refactor processor factories to use config check
  logprep/processor/datetime_extractor/factory.py
  logprep/processor/domain_label_extractor/factory.py
  logprep/processor/labeler/factory.py
  tests/unit/processor/domain_label_extractor/test_domain_label_extractor_factory.py
Labels: enhancement

#74 Fix 73 consistency for applying rules
  logprep/framework/rule_tree/rule_tree.py
  logprep/processor/base/processor.py
  logprep/processor/base/rule.py
  logprep/processor/clusterer/processor.py
  logprep/processor/clusterer/signature_calculation/signature_phase.py
  logprep/processor/datetime_extractor/factory.py
  logprep/processor/datetime_extractor/processor.py
  logprep/processor/domain_label_extractor/processor.py
  logprep/processor/domain_resolver/factory.py
  logprep/processor/domain_resolver/processor.py
  logprep/processor/generic_adder/processor.py
  logprep/processor/generic_resolver/processor.py
  logprep/processor/geoip_enricher/processor.py
  logprep/processor/labeler/processor.py
  logprep/processor/list_comparison/processor.py
  logprep/processor/normalizer/processor.py
  logprep/processor/normalizer/rule.py
  logprep/processor/pre_detector/ip_alerter.py
  logprep/processor/pre_detector/processor.py
  logprep/processor/processor_factory.py
  logprep/processor/processor_strategy.py
  logprep/processor/pseudonymizer/processor.py
  logprep/processor/template_replacer/processor.py
  logprep/util/helper.py
  logprep/util/schema_and_rule_checker.py
  logprep/util/time_measurement.py
  tests/testdata/unit/clusterer/rules/generic/rules.json
  tests/testdata/unit/domain_resolver/rules/domain_resolver.json
  tests/testdata/unit/domain_resolver/rules/generic/domain_resolver.json
  tests/testdata/unit/domain_resolver/rules/specific/domain_resolver.json
  tests/unit/framework/rule_tree/test_rule_tree.py
  tests/unit/processor/base.py
  tests/unit/processor/clusterer/test_clusterer.py
  tests/unit/processor/datetime_extractor/test_date_time_extractor.py
  tests/unit/processor/domain_resolver/test_domain_resolver.py
  tests/unit/processor/geoip_enricher/test_geoip_enricher.py
  tests/unit/processor/list_comparison/test_list_comparison.py
  tests/unit/processor/normalizer/test_normalizer.py
  tests/unit/processor/pseudonymizer/test_pseudonymizer.py
  tests/unit/processor/test_processor_strategy.py
  tests/unit/util/test_helper.py
Labels: bug, enhancement
