Repository fkie-cad/Logprep, pull requests merged in 2022-02, with the labels that each got.

#22 Add selective extraction processor
  doc/source/user_manual/configuration/processor.rst
  doc/source/user_manual/introduction.rst
  logprep/processor/selective_extractor/__init__.py
  logprep/processor/selective_extractor/factory.py
  logprep/processor/selective_extractor/processor.py
  tests/acceptance/test_full_message_pass_with_hmac.py
  tests/acceptance/test_selective_extractor_full_pipeline_pass.py
  tests/acceptance/util.py
  tests/testdata/acceptance/selective_extractor/extract.jsonl
  tests/testdata/acceptance/selective_extractor/whitelist.txt
  tests/testdata/unit/selective_extractor/test_extraction_list.txt
  tests/unit/processor/list_comparison/test_list_comparison.py
  tests/unit/processor/selective_extractor/__init__.py
  tests/unit/processor/selective_extractor/test_selective_extractor.py
Labels: documentation, enhancement

#23 Add dotted output fields for the geoip enricher processor
  doc/source/user_manual/rule_language.rst
  logprep/processor/geoip_enricher/processor.py
  tests/testdata/unit/geoip_enricher/rules/geoip_all.json
  tests/unit/processor/geoip_enricher/test_geoip_enricher.py
Labels: documentation, enhancement

#24 Refactor code to decouple source code from test code
  logprep/run_logprep.py
  logprep/util/auto_rule_tester.py
  logprep/util/helper.py
  logprep/util/json_handling.py
  logprep/util/rule_dry_runner.py
  tests/acceptance/test_full_message_pass_with_hmac.py
  tests/acceptance/test_pre_detection.py
  tests/acceptance/test_selective_extractor_full_pipeline_pass.py
  tests/acceptance/test_wineventlog_normalization.py
  tests/acceptance/test_wineventlog_processing.py
  tests/acceptance/test_wineventlog_pseudonymization.py
  tests/acceptance/util.py
Labels: enhancement

#25 Fix selective extractor stats
  logprep/util/processor_stats.py
Labels: bug
