Repository fkie-cad/Logprep, pull requests merged in 2022-12, with the labels that each got.

#236 Fix count of number_of_processed_events in input connector
  CHANGELOG.md
  logprep/abc/input.py
  tests/unit/connector/base.py
Labels: bug

#243 241 feature load files from http is broken because of file validator
  .github/workflows/ci.yml
  .github/workflows/main.yml
  logprep/processor/labeler/processor.py
  logprep/processor/normalizer/processor.py
  logprep/processor/pre_detector/processor.py
  logprep/processor/pseudonymizer/processor.py
  logprep/processor/template_replacer/processor.py
  tests/acceptance/test_full_configuration.py
  tests/acceptance/test_http_input.py
  tests/acceptance/util.py
  tests/unit/processor/datetime_extractor/test_datetime_extractor.py
  tests/unit/processor/datetime_extractor/test_datetime_extractor_rule.py
  tests/unit/processor/pre_detector/test_pre_detector.py
Labels: bug

#248 fix mermaid documentation output
  doc/source/conf.py
Labels: bug

#247 Fix deleter unbound local error
  logprep/processor/deleter/rule.py
  tests/unit/processor/deleter/test_deleter_rule.py
Labels: bug

#249 upgrade certifi
  requirements.in
  requirements.txt
  requirements_dev.txt
Labels: bug

#242 Add timestamp_differ processor
  CHANGELOG.md
  doc/source/development/coding_examples.rst
  doc/source/development/notebooks/processor_examples/timestamp_differ.ipynb
  doc/source/user_manual/configuration/processor.rst
  doc/source/user_manual/configuration/rules.rst
  logprep/abc/processor.py
  logprep/processor/calculator/processor.py
  logprep/processor/calculator/rule.py
  logprep/processor/timestamp_differ/__init__.py
  logprep/processor/timestamp_differ/processor.py
  logprep/processor/timestamp_differ/rule.py
  logprep/registry.py
  tests/testdata/unit/timestamp_differ/generic_rules/timestamp_differ_rule.json
  tests/testdata/unit/timestamp_differ/specific_rules/timestamp_differ_rule.json
  tests/unit/processor/timestamp_differ/__init__.py
  tests/unit/processor/timestamp_differ/test_timestamp_differ.py
  tests/unit/processor/timestamp_differ/test_timestamp_differ_rule.py
Labels: enhancement

#226 Add requester processor
  CHANGELOG.md
  doc/source/user_manual/configuration/processor.rst
  doc/source/user_manual/configuration/rules.rst
  logprep/processor/calculator/processor.py
  logprep/processor/calculator/rule.py
  logprep/processor/field_manager/rule.py
  logprep/processor/requester/__init__.py
  logprep/processor/requester/processor.py
  logprep/processor/requester/rule.py
  logprep/processor/timestamp_differ/processor.py
  logprep/processor/timestamp_differ/rule.py
  logprep/registry.py
  logprep/util/helper.py
  requirements.in
  requirements.txt
  requirements_dev.in
  requirements_dev.txt
  tests/testdata/unit/requester/generic_rules/requester.json
  tests/testdata/unit/requester/specific_rules/requester.json
  tests/unit/processor/requester/__init__.py
  tests/unit/processor/requester/test_requester.py
  tests/unit/processor/requester/test_requester_rule.py
Labels: enhancement

#251 refactor pipeline
  logprep/factory.py
  logprep/framework/pipeline.py
  tests/acceptance/test_http_input.py
  tests/acceptance/util.py
  tests/unit/framework/test_pipeline.py
Labels: refactoring

#255 Hide units by default
  doc/source/development/notebooks/processor_examples/timestamp_differ.ipynb
  logprep/processor/timestamp_differ/processor.py
  logprep/processor/timestamp_differ/rule.py
  tests/unit/processor/timestamp_differ/test_timestamp_differ.py
Labels: enhancement

#256 add requester example
  doc/source/development/coding_examples.rst
  doc/source/development/notebooks/processor_examples/requester.ipynb
  doc/source/development/notebooks/processor_examples/requester_api_example.json
  tests/acceptance/test_full_configuration.py
  tests/acceptance/util.py
Labels: enhancement

#258 fix version output
  README.md
  logprep/abc/getter.py
  logprep/connector/confluent_kafka/input.py
  logprep/run_logprep.py
  logprep/util/configuration.py
  logprep/util/getter.py
  quickstart/exampledata/config/pipeline.yml
  tests/testdata/config/config-docker.yml
  tests/testdata/config/config.yml
  tests/testdata/config/config2.yml
  tests/unit/test_run_logprep.py
  tests/unit/util/test_getter.py
Labels: bug

#263 fix artifacts load during process time
  logprep/processor/domain_label_extractor/processor.py
  logprep/processor/domain_resolver/processor.py
  logprep/processor/geoip_enricher/processor.py
  tests/unit/processor/domain_label_extractor/test_domain_label_extractor.py
  tests/unit/processor/domain_resolver/test_domain_resolver.py
  tests/unit/processor/geoip_enricher/test_geoip_enricher.py
Labels: bug

#264 Resolve deprecation warnings in tests for deleter and datetime_extractor
  tests/testdata/unit/datetime_extractor/rules/generic/datetime_extractor.json
  tests/testdata/unit/datetime_extractor/rules/specific/datetime_extractor.json
  tests/testdata/unit/deleter/rules/generic/generic_delete.json
  tests/testdata/unit/deleter/rules/specific/delete_test.json
  tests/testdata/unit/deleter/rules/specific/specific_delete.json
  tests/unit/processor/datetime_extractor/test_datetime_extractor_rule.py
  tests/unit/processor/deleter/test_deleter_rule.py
Labels: refactoring

#265 resolve deprecation warnings in test for domain_label_extractor and domain_resolver
  logprep/processor/domain_label_extractor/rule.py
  tests/testdata/unit/domain_label_extractor/rules/generic/domain_label_extractor_gen.json
  tests/testdata/unit/domain_label_extractor/rules/specific/domain_label_extractor.json
  tests/testdata/unit/domain_resolver/rules/generic/domain_resolver.yml
  tests/testdata/unit/domain_resolver/rules/specific/domain_resolver.json
  tests/unit/processor/domain_label_extractor/test_domain_label_extractor_rule.py
  tests/unit/processor/domain_resolver/test_domain_resolver.py
  tests/unit/processor/domain_resolver/test_domain_resolver_rule.py
Labels: refactoring

#266 resolve deprecation warnings in test for dropper
  quickstart/exampledata/rules/dropper/generic/example_rule.yml
  quickstart/exampledata/rules/dropper/specific/example_rule.yml
  tests/testdata/acceptance/dropper/rules/drop_field.json
  tests/testdata/auto_tests/dropper/rules/generic/drop_field.json
  tests/testdata/auto_tests/dropper/rules/specific/drop_field.json
  tests/testdata/unit/dropper/rules/generic/drop_field.json
  tests/testdata/unit/dropper/rules/specific/drop_field.json
  tests/unit/processor/deleter/test_deleter_rule.py
  tests/unit/processor/dropper/test_dropper.py
  tests/unit/processor/dropper/test_dropper_rule.py
Labels: refactoring

#267 resolve deprecation warnings in test for geoip_enricher
  tests/testdata/unit/geoip_enricher/rules/generic/geoip_all.json
  tests/testdata/unit/geoip_enricher/rules/specific/geoip_all.json
  tests/unit/processor/geoip_enricher/test_geoip_enricher_rule.py
Labels: refactoring

#269 resolve deprecation warnings in test for list_comparison
  tests/testdata/unit/list_comparison/rules/generic/user_check.json
  tests/testdata/unit/list_comparison/rules/specific/user_check_specific.json
  tests/unit/processor/list_comparison/test_list_comparison.py
  tests/unit/processor/list_comparison/test_list_comparison_rule.py
Labels: refactoring
