Repository fkie-cad/Logprep, pull requests merged in 2022-08, with the labels that each got.

#149 Add logprep and configuration version to event
  .gitignore
  CHANGELOG.md
  doc/source/user_manual/configuration/connector.rst
  logprep/connector/confluent_kafka.py
  logprep/framework/pipeline.py
  logprep/framework/pipeline_manager.py
  logprep/util/configuration.py
  tests/acceptance/test_full_message_pass_with_hmac.py
  tests/acceptance/util.py
  tests/unit/connector/test_confluent_kafka.py
  tests/unit/framework/test_pipeline.py
  tests/unit/util/test_configuration.py
Labels: enhancement

#144 Extend documentation for new processor specific metrics
  doc/source/development/processor_how_to.rst
  logprep/processor/dropper/processor.py
Labels: documentation

#145 Expose logprep and config version in metrics
  CHANGELOG.md
  logprep/metrics/metric_targets.py
  logprep/util/prometheus_exporter.py
  tests/unit/metrics/test_metric_targets.py
Labels: enhancement

#152 Fix selective extractor output
  CHANGELOG.md
  logprep/processor/selective_extractor/processor.py
  tests/unit/processor/selective_extractor/test_selective_extractor.py
Labels: bug

#153 Fix pipeline config attribute name
  logprep/framework/pipeline.py
  tests/unit/framework/test_pipeline.py
Labels: bug

#155 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#154 Dev improve dry run
  CHANGELOG.md
  doc/source/user_manual/dry_run.rst
  logprep/input/json_input.py
  logprep/input/jsonl_input.py
  logprep/util/helper.py
  logprep/util/json_handling.py
  logprep/util/rule_dry_runner.py
  tests/testdata/config/config-docker.yml
  tests/testdata/config/config-dry-run.yml
  tests/testdata/config/config.yml
  tests/testdata/config/config2.yml
  tests/unit/util/test_rule_dry_runner.py
  tests/unit/util/tests_json_handling.py
Labels: enhancement

#159 add file excludes to vscode settings
  .vscode/settings.json
Labels: enhancement

#158 Fix preprocessor config validation
  CHANGELOG.md
  logprep/connector/confluent_kafka.py
  tests/acceptance/test_preprocessors.py
Labels: bug

#157 Allow normalizer to write grok_failure fields
  CHANGELOG.md
  doc/source/user_manual/rule_language.rst
  logprep/processor/normalizer/processor.py
  logprep/processor/normalizer/rule.py
  tests/unit/processor/normalizer/test_normalizer.py
Labels: enhancement

#164 Update changelog for v3.3.0 release
  CHANGELOG.md
Labels: documentation

#83 Add es output connector and split kafka connector
  CHANGELOG.md
  doc/source/user_manual/configuration/connector.rst
  logprep/connector/confluent_kafka.py
  logprep/connector/confluent_kafka_shared.py
  logprep/connector/connector_factory.py
  logprep/input/confluent_kafka_input.py
  logprep/input/input.py
  logprep/output/confluent_kafka_output.py
  logprep/output/es_output.py
  logprep/processor/pre_detector/ip_alerter.py
  logprep/run_logprep.py
  requirements.in
  requirements.txt
  requirements_dev.txt
  tests/acceptance/util.py
  tests/unit/connector/test_confluent_kafka.py
  tests/unit/connector/test_connector_factory.py
  tests/unit/connector/test_elasticsearch_output.py
  tests/unit/connector/test_elasticsearch_output_factory.py
  tests/unit/framework/test_pipeline.py
Labels: enhancement

#169 Increase Test Coverage for Connectors
  logprep/input/dummy_input.py
  logprep/input/input.py
  logprep/input/json_input.py
  logprep/input/jsonl_input.py
  logprep/output/console_output.py
  logprep/output/output.py
  logprep/output/writing_output.py
  tests/unit/connector/test_console_output.py
  tests/unit/connector/test_dummy_input.py
  tests/unit/connector/test_json_input.py
  tests/unit/connector/test_jsonl_input.py
  tests/unit/connector/test_writing_output.py
Labels: refactoring

#170 Remove unused code
  logprep/abc/processor.py
  logprep/annotator/__init__.py
  logprep/connector/confluent_kafka_shared.py
  logprep/input/confluent_kafka_input.py
Labels: refactoring

#173 refactor connectors part 1
  logprep/abc/input.py
  logprep/abc/output.py
  logprep/connector/confluent_kafka/__init__.py
  logprep/connector/confluent_kafka/common.py
  logprep/connector/confluent_kafka/input.py
  logprep/connector/confluent_kafka/output.py
  logprep/connector/connector_factory.py
  logprep/connector/console/__init__.py
  logprep/connector/console/output.py
  logprep/connector/dummy/__init__.py
  logprep/connector/dummy/input.py
  logprep/connector/dummy/output.py
  logprep/connector/elasticsearch/__init__.py
  logprep/connector/elasticsearch/output.py
  logprep/connector/json/__init__.py
  logprep/connector/json/input.py
  logprep/connector/jsonl/__init__.py
  logprep/connector/jsonl/input.py
  logprep/connector/jsonl/output.py
  logprep/framework/pipeline.py
  tests/acceptance/util.py
  tests/unit/connector/test_confluent_kafka.py
  tests/unit/connector/test_connector_factory.py
  tests/unit/connector/test_console_output.py
  tests/unit/connector/test_dummy_input.py
  tests/unit/connector/test_dummy_output.py
  tests/unit/connector/test_elasticsearch_output.py
  tests/unit/connector/test_elasticsearch_output_factory.py
  tests/unit/connector/test_json_input.py
  tests/unit/connector/test_jsonl_input.py
  tests/unit/connector/test_writing_output.py
  tests/unit/framework/test_pipeline.py
Labels: refactoring
