Repository fkie-cad/Logprep, pull requests merged in 2023-03, with the labels that each got.

#331 update changelog bump `attrs` requirement
  CHANGELOG.md
Labels: documentation

#325 make properties configurable in ip_informer rule
  logprep/processor/ip_informer/processor.py
  logprep/processor/ip_informer/rule.py
  tests/unit/processor/ip_informer/test_ip_informer.py
  tests/unit/processor/ip_informer/test_ip_informer_rule.py
Labels: enhancement

#333 fix handle template errors
  CHANGELOG.md
  doc/source/user_manual/configuration/configurationdata.rst
  logprep/abc/getter.py
  logprep/run_logprep.py
  logprep/util/configuration.py
  tests/acceptance/test_full_configuration.py
  tests/acceptance/test_http_input.py
  tests/acceptance/util.py
  tests/unit/util/test_configuration.py
  tests/unit/util/test_getter.py
Labels: bug

#336 Fix metrics for multiple outputs
  CHANGELOG.md
  logprep/abc/connector.py
  logprep/framework/pipeline.py
  logprep/metrics/metric_exposer.py
  tests/acceptance/test_full_configuration.py
  tests/acceptance/util.py
  tests/unit/framework/test_pipeline.py
  tests/unit/metrics/test_metric_exposer.py
  tests/unit/metrics/test_metric_targets.py
Labels: bug

#339 Fixed broken link in README.md
  README.md
Labels: documentation

#337 remove verification of configuration in pipeline manager and run_logprep
  logprep/framework/pipeline_manager.py
  logprep/run_logprep.py
  tests/unit/test_run_logprep.py
Labels: enhancement

#342 make broader exception for search connection test
  logprep/connector/elasticsearch/output.py
  logprep/connector/opensearch/output.py
Labels: bug

#318 Apply processors multiple times
  CHANGELOG.md
  logprep/processor/processor_strategy.py
  tests/acceptance/test_pre_detection.py
  tests/testdata/acceptance/expected_result/pre_detection_expected.jsonl
  tests/testdata/input_logdata/kafka_raw_event_for_pre_detector.jsonl
  tests/testdata/unit/list_comparison/rules/generic/user_check.json
  tests/unit/processor/list_comparison/test_list_comparison.py
  tests/unit/processor/test_processor_strategy.py
Labels: enhancement

#346 fix non-deterministic behavior and add test
  logprep/processor/base/rule.py
  logprep/processor/processor_strategy.py
  tests/unit/processor/test_processor_strategy.py
Labels: bug

#352 Fix dry_runner to deal with multiple outputs
  logprep/framework/pipeline.py
  logprep/util/aggregating_logger.py
  logprep/util/auto_rule_tester/auto_rule_corpus_tester.py
  logprep/util/configuration.py
  logprep/util/rule_dry_runner.py
  tests/acceptance/util.py
  tests/unit/util/test_configuration.py
  tests/unit/util/test_rule_dry_runner.py
Labels: bug

#351 replace json.loads with msgspec to improve input connector performance
  logprep/connector/confluent_kafka/input.py
  logprep/connector/confluent_kafka/output.py
  requirements.in
  requirements.txt
  requirements_dev.txt
Labels: enhancement

#357 add kafka advanced config option
  CHANGELOG.md
  logprep/connector/confluent_kafka/input.py
  logprep/connector/confluent_kafka/output.py
  logprep/processor/generic_adder/processor.py
  logprep/util/auto_rule_tester/auto_rule_tester.py
  tests/unit/connector/test_confluent_kafka_input.py
  tests/unit/connector/test_confluent_kafka_output.py
  tests/unit/processor/amides/test_amides.py
Labels: enhancement
