Repository fkie-cad/Logprep, pull requests merged in 2023-11, with the labels that each got.

#467 refactor pre_detector
  logprep/processor/pre_detector/processor.py
  tests/unit/processor/pre_detector/test_pre_detector.py
Labels: refactoring

#474 Update publish-release-to-pypi.yml to use trusted publishing
  .github/workflows/publish-release-to-pypi.yml
Labels: bug, enhancement

#471 Improve error message on empty rule filter
  CHANGELOG.md
  logprep/processor/base/rule.py
  tests/unit/processor/test_processor_rule.py
Labels: enhancement
