Repository fkie-cad/Logprep, pull requests merged in 2023-10, with the labels that each got.

#449 fix main pipeline
  .github/workflows/main.yml
Labels: bug

#452 fix memory leak
  logprep/util/helper.py
Labels: bug

#450 add grafana and prometheus stack to quickstart
  CHANGELOG.md
  README.md
  quickstart/docker-compose.yml
  quickstart/exampledata/config/grafana/dashboards/logprep-provider.yml
  quickstart/exampledata/config/grafana/datasources/prometheus.yml
  quickstart/exampledata/config/prometheus/logprep.yml
  quickstart/exampledata/config/prometheus/prometheus.yml
Labels: enhancement

#454 fix CVE-2023-43804
  CHANGELOG.md
  requirements.in
  requirements.txt
  requirements_dev.txt
Labels: bug

#453 add inline rule config feature to pipline config
  CHANGELOG.md
  logprep/abc/processor.py
  logprep/processor/base/rule.py
  logprep/util/schema_and_rule_checker.py
  quickstart/exampledata/config/pipeline.yml
  tests/unit/framework/test_pipeline.py
  tests/unit/test_factory.py
Labels: enhancement

#456 Remove MetricFileTarget
  CHANGELOG.md
  doc/source/user_manual/configuration/metrics.rst
  logprep/framework/pipeline.py
  logprep/framework/pipeline_manager.py
  logprep/metrics/metric.py
  logprep/metrics/metric_exposer.py
  logprep/metrics/metric_targets.py
  logprep/runner.py
  logprep/util/configuration.py
  logprep/util/prometheus_exporter.py
  quickstart/exampledata/config/pipeline.yml
  tests/acceptance/test_full_configuration.py
  tests/unit/framework/test_pipeline.py
  tests/unit/framework/test_pipeline_manager.py
  tests/unit/metrics/test_metric_exposer.py
  tests/unit/metrics/test_metric_targets.py
  tests/unit/test_runner.py
  tests/unit/util/test_configuration.py
  tests/unit/util/test_prometheus_exporter.py
Labels: refactoring

#451 remove process_strategy and mermaid
  doc/requirements.txt
  doc/source/conf.py
  doc/source/development/index.rst
  doc/source/user_manual/introduction.rst
  logprep/abc/processor.py
  logprep/processor/processor_strategy.py
  logprep/run_logprep.py
  tests/unit/processor/base.py
  tests/unit/processor/test_process.py
  tests/unit/test_run_logprep.py
Labels: refactoring

#444 rewrite kafka connector
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  CHANGELOG.md
  doc/source/_templates/defaults-renderer.tmpl
  doc/source/user_manual/configuration/configurationdata.rst
  logprep/abc/component.py
  logprep/abc/input.py
  logprep/connector/confluent_kafka/input.py
  logprep/connector/confluent_kafka/output.py
  logprep/connector/elasticsearch/output.py
  logprep/framework/pipeline.py
  logprep/util/prometheus_exporter.py
  logprep/util/validators.py
  quickstart/docker-compose.yml
  quickstart/exampledata/config/pipeline.yml
  tests/acceptance/test_full_configuration.py
  tests/acceptance/test_http_input.py
  tests/testdata/config/config-docker.yml
  tests/testdata/config/config.yml
  tests/testdata/config/config2.yml
  tests/testdata/kafka_stats_return_value.json
  tests/unit/connector/test_confluent_kafka_common.py
  tests/unit/connector/test_confluent_kafka_input.py
  tests/unit/connector/test_confluent_kafka_output.py
  tests/unit/connector/test_file_input_default_config.py
  tests/unit/connector/test_real_kafka.py
  tests/unit/util/test_configuration.py
Labels: enhancement

#457 add option to ignore missing fields in field_manager
  CHANGELOG.md
  logprep/abc/processor.py
  logprep/processor/amides/rule.py
  logprep/processor/calculator/rule.py
  logprep/processor/concatenator/processor.py
  logprep/processor/datetime_extractor/rule.py
  logprep/processor/dissector/processor.py
  logprep/processor/domain_label_extractor/rule.py
  logprep/processor/domain_resolver/rule.py
  logprep/processor/field_manager/processor.py
  logprep/processor/field_manager/rule.py
  logprep/processor/geoip_enricher/rule.py
  logprep/processor/grokker/processor.py
  logprep/processor/ip_informer/processor.py
  logprep/processor/key_checker/rule.py
  logprep/processor/list_comparison/rule.py
  logprep/processor/requester/rule.py
  logprep/processor/selective_extractor/processor.py
  logprep/processor/selective_extractor/rule.py
  logprep/processor/string_splitter/rule.py
  logprep/processor/timestamp_differ/rule.py
  logprep/processor/timestamper/rule.py
  tests/unit/processor/calculator/test_calculator.py
  tests/unit/processor/concatenator/test_concatenator.py
  tests/unit/processor/dissector/test_dissector.py
  tests/unit/processor/field_manager/test_field_manager.py
  tests/unit/processor/grokker/test_grokker.py
  tests/unit/processor/ip_informer/test_ip_informer.py
  tests/unit/processor/selective_extractor/test_selective_extractor.py
Labels: enhancement

#461 prepare release 7.0.0
  CHANGELOG.md
Labels: documentation
