Repository fkie-cad/Logprep, pull requests merged in 2024-10, with the labels that each got.

#677 Fix exporter restart
  examples/compose/docker-compose.yml
  examples/exampledata/config/http_pipeline.yml
  examples/exampledata/config/pipeline.yml
  logprep/connector/jsonl/output.py
  logprep/framework/pipeline_manager.py
  logprep/metrics/exporter.py
  logprep/run_logprep.py
  logprep/runner.py
  logprep/util/http.py
  logprep/util/logging.py
  tests/acceptance/test_config_refresh.py
  tests/acceptance/test_full_configuration.py
  tests/acceptance/util.py
  tests/unit/framework/test_pipeline_manager.py
  tests/unit/metrics/test_exporter.py
  tests/unit/test_runner.py
Labels: bug

#679 Ensure kafka output flushes queue on shutdown
  CHANGELOG.md
  logprep/connector/confluent_kafka/output.py
  tests/unit/connector/test_confluent_kafka_output.py
Labels: bug

#682 Remove unneeded dependencies
  Dockerfile
  pyproject.toml
Labels: bug

#678 Remove broken kafka implementations
  CHANGELOG.md
  logprep/connector/confluent_kafka/input.py
  tests/unit/connector/test_confluent_kafka_input.py
Labels: bug

#683 Fix docker image and avoid implicit setuptools runtime dependency
  Dockerfile
  logprep/util/grok/grok.py
Labels: bug

#684 test container image before push
  .github/workflows/ci.yml
Labels: enhancement

#686 make `terminationGracePeriodSeconds` configurable.
  CHANGELOG.md
  charts/logprep/Chart.yaml
  charts/logprep/templates/deployment.yaml
  charts/logprep/values.yaml
Labels: enhancement

#594 Dev autoruletester refactoring
  examples/exampledata/rules/labeler/generic/example_rule.yml
  examples/exampledata/rules/pre_detector/generic/example_rule.yml
  logprep/abc/processor.py
  logprep/processor/clusterer/processor.py
  logprep/util/auto_rule_tester/auto_rule_tester.py
  pyproject.toml
  requirements.in
  requirements.txt
  tests/testdata/auto_tests/dummy/rule.yml
  tests/testdata/auto_tests/dummy/rule_test.json
  tests/testdata/auto_tests/labeler/rules/generic/auto_test_labeling_match_test.json
  tests/unit/util/test_auto_rule_tester.py
Labels: refactoring
