Repository fkie-cad/Logprep, pull requests merged in 2024-04, with the labels that each got.

#562 make pipeline index stable
  CHANGELOG.md
  logprep/framework/pipeline_manager.py
  tests/unit/framework/test_pipeline_manager.py
Labels: bug

#566 fix http connector only first process working
  CHANGELOG.md
  logprep/connector/http/input.py
  logprep/framework/pipeline.py
  logprep/framework/pipeline_manager.py
  quickstart/exampledata/config/http_pipeline.yml
  tests/unit/connector/test_http_input.py
  tests/unit/framework/test_pipeline_manager.py
Labels: bug

#559 Add overview with best practices to docs
  CHANGELOG.md
  doc/source/_static/css/custom_theme.css
  doc/source/_templates/defaults-renderer.tmpl
  doc/source/conf.py
  doc/source/custom_extensions/security_best_practices.py
  doc/source/development/programaticly_start_logprep.rst
  doc/source/user_manual/configuration/index.rst
  doc/source/user_manual/configuration/input.rst
  doc/source/user_manual/configuration/output.rst
  doc/source/user_manual/configuration/pipeline.rst
  doc/source/user_manual/index.rst
  doc/source/user_manual/introduction.rst
  doc/source/user_manual/security_best_practices.rst
  logprep/abc/processor.py
  logprep/connector/confluent_kafka/input.py
  logprep/connector/confluent_kafka/output.py
  logprep/connector/elasticsearch/output.py
  logprep/connector/http/input.py
  logprep/connector/opensearch/output.py
  logprep/connector/s3/output.py
  logprep/processor/amides/processor.py
  logprep/processor/domain_resolver/processor.py
  logprep/processor/generic_adder/processor.py
  logprep/processor/labeler/processor.py
  logprep/processor/list_comparison/rule.py
  logprep/processor/pseudonymizer/processor.py
  logprep/processor/requester/processor.py
  logprep/util/configuration.py
  logprep/util/getter.py
  pyproject.toml
Labels: documentation

#568 fix broken gracefull shutdown
  CHANGELOG.md
  logprep/connector/http/input.py
  logprep/framework/pipeline_manager.py
  logprep/run_logprep.py
Labels: bug

#571 Fix grokker rules that have fields with common prefixes
  CHANGELOG.md
  logprep/processor/grokker/rule.py
  tests/unit/processor/grokker/test_grokker.py
Labels: bug

#576 export metrics via uvicorn asgi app
  CHANGELOG.md
  logprep/connector/http/input.py
  logprep/metrics/exporter.py
  logprep/util/configuration.py
  logprep/util/http.py
  quickstart/exampledata/config/http_pipeline.yml
  tests/acceptance/test_full_configuration.py
  tests/unit/connector/test_http_input.py
  tests/unit/metrics/test_exporter.py
  tests/unit/util/test_configuration.py
Labels: enhancement

#578 add http input connector metrics
  CHANGELOG.md
  logprep/connector/http/input.py
  logprep/connector/s3/output.py
  tests/unit/connector/test_http_input.py
Labels: enhancement

#580 fix bug prometheus exporter server uvicorn only on localhost
  CHANGELOG.md
  logprep/metrics/exporter.py
  tests/unit/metrics/test_exporter.py
Labels: bug
