Repository fkie-cad/Logprep, pull requests merged in 2024-12, with the labels that each got.

#720 Improve test_http_input execution speed
  logprep/connector/file/input.py
  logprep/connector/http/input.py
  tests/acceptance/test_http_input_with_requests.py
  tests/unit/connector/test_http_input.py
Labels: enhancement

#718 remove-tldextract-and-urlextract-dependencies
  CHANGELOG.md
  logprep/processor/domain_label_extractor/processor.py
  logprep/processor/domain_resolver/processor.py
  logprep/processor/pseudonymizer/processor.py
  logprep/util/url/__init__.py
  logprep/util/url/tldlist/public_suffix_list.dat
  logprep/util/url/url.py
  pyproject.toml
  tests/testdata/mock_external/tld_list.dat
  tests/unit/processor/domain_label_extractor/test_domain_label_extractor.py
  tests/unit/processor/domain_resolver/test_domain_resolver.py
  tests/unit/processor/pseudonymizer/test_pseudonymizer.py
  tests/unit/util/test_url.py
Labels: refactoring

#723 Fix timestamp differ rule doc
  CHANGELOG.md
  logprep/processor/timestamp_differ/rule.py
Labels: bug, documentation

#724 add shut_down method to opensearch output connector
  CHANGELOG.md
  logprep/connector/opensearch/output.py
  tests/unit/connector/test_opensearch_output.py
Labels: bug

#722 remove sql from generic_adder
  .gitignore
  CHANGELOG.md
  logprep/processor/generic_adder/mysql_connector.py
  logprep/processor/generic_adder/processor.py
  logprep/processor/generic_adder/rule.py
  pyproject.toml
  tests/testdata/unit/generic_adder/rules/generic/rules.json
  tests/unit/processor/generic_adder/test_generic_adder.py
Labels: enhancement

#729 add signing to action
  .github/workflows/ci.yml
  .github/workflows/publish-latest-dev-release-to-github.yml
  .github/workflows/publish-release-to-pypi.yml
  CHANGELOG.md
  README.md
Labels: enhancement

#730 add SBOM to images
  .github/workflows/ci.yml
  .github/workflows/publish-release-to-pypi.yml
  CHANGELOG.md
  README.md
Labels: enhancement

#732 replace container build steps with reusable workflow
  .github/workflows/ci.yml
  .github/workflows/container-build.yml
  .github/workflows/publish-latest-dev-release-to-github.yml
  .github/workflows/publish-release-to-pypi.yml
Labels: enhancement

#733 fix build-version in dev release
  .github/workflows/publish-latest-dev-release-to-github.yml
Labels: enhancement
