Repository fkie-cad/Logprep, pull requests merged in 2024-06, with the labels that each got.

#591 refactor http generator output to http_output connector
  CHANGELOG.md
  doc/source/user_manual/configuration/input.rst
  doc/source/user_manual/configuration/output.rst
  logprep/abc/connector.py
  logprep/connector/http/input.py
  logprep/connector/http/output.py
  logprep/factory.py
  logprep/framework/pipeline_manager.py
  logprep/generator/http/controller.py
  logprep/generator/http/input.py
  logprep/generator/http/output.py
  logprep/generator/http/reporter.py
  logprep/registry.py
  logprep/run_logprep.py
  quickstart/exampledata/config/http_pipeline.yml
  tests/unit/connector/test_http_input.py
  tests/unit/connector/test_http_output.py
  tests/unit/framework/test_pipeline_manager.py
  tests/unit/generator/http/test_controller.py
  tests/unit/generator/http/test_input.py
  tests/unit/generator/http/test_output.py
  tests/unit/generator/http/test_reporter.py
  tests/unit/test_run_logprep.py
Labels: refactoring

#599 add depseudo tools
  CHANGELOG.md
  doc/source/user_manual/execution.rst
  logprep/processor/pseudonymizer/encrypter.py
  logprep/run_logprep.py
  logprep/util/pseudo/__init__.py
  logprep/util/pseudo/commands/__init__.py
  logprep/util/pseudo/commands/depseudonymize.py
  logprep/util/pseudo/commands/generate_keys.py
  logprep/util/pseudo/commands/pseudonymize.py
  logprep/util/pseudo/depseudonymizer/__init__.py
  logprep/util/pseudo/depseudonymizer/depseudonymizer.py
  logprep/util/pseudo/keygenerator/__init__.py
  logprep/util/pseudo/keygenerator/generate_rsa_key.py
  tests/unit/util/pseudo/__init__.py
  tests/unit/util/pseudo/test_depseudomize.py
  tests/unit/util/pseudo/test_generate_rsa_key.py
  tests/unit/util/pseudo/test_pseudonymize.py
Labels: enhancement

#601 add calling setup during configuration verify
  CHANGELOG.md
  logprep/abc/component.py
  logprep/connector/confluent_kafka/input.py
  logprep/connector/confluent_kafka/output.py
  logprep/connector/dummy/output.py
  logprep/connector/file/input.py
  logprep/processor/list_comparison/processor.py
  logprep/util/configuration.py
  tests/acceptance/test_full_configuration.py
  tests/unit/component/base.py
  tests/unit/connector/test_confluent_kafka_input.py
  tests/unit/connector/test_dummy_output.py
  tests/unit/connector/test_elasticsearch_output.py
  tests/unit/connector/test_jsonl_output.py
  tests/unit/connector/test_opensearch_output.py
  tests/unit/connector/test_s3_output.py
  tests/unit/processor/list_comparison/test_list_comparison.py
  tests/unit/util/test_auto_rule_tester.py
  tests/unit/util/test_configuration.py
Labels: bug

#604 fix quickstart compose setup for WSL
  quickstart/docker-compose.yml
  quickstart/exampledata/config/grafana/dashboards/sample.yaml
  quickstart/exampledata/config/grafana/datasources/sample.yaml
Labels: bug

#602 revise restart behavior
  .vscode/extensions.json
  CHANGELOG.md
  doc/source/user_manual/execution.rst
  logprep/framework/pipeline_manager.py
  logprep/run_logprep.py
  logprep/runner.py
  logprep/util/configuration.py
  logprep/util/defaults.py
  tests/acceptance/test_amides.py
  tests/acceptance/util.py
  tests/unit/framework/test_pipeline_manager.py
  tests/unit/test_run_logprep.py
  tests/unit/test_runner.py
Labels: enhancement

#600 add option to pseudonymizer to use different encryption modes
  CHANGELOG.md
  doc/source/user_manual/execution.rst
  logprep/processor/pseudonymizer/encrypter.py
  logprep/processor/pseudonymizer/processor.py
  logprep/util/defaults.py
  logprep/util/pseudo/commands/depseudonymize.py
  logprep/util/pseudo/commands/pseudonymize.py
  logprep/util/pseudo/decrypter.py
  logprep/util/pseudo/depseudonymizer/__init__.py
  logprep/util/pseudo/depseudonymizer/depseudonymizer.py
  logprep/util/pseudo/encrypter.py
  tests/unit/processor/pseudonymizer/test_encrypter.py
  tests/unit/processor/pseudonymizer/test_pseudonymizer.py
  tests/unit/test_run_logprep.py
  tests/unit/util/pseudo/test_decrpyter.py
  tests/unit/util/pseudo/test_depseudomize.py
  tests/unit/util/pseudo/test_encrypter.py
  tests/unit/util/pseudo/test_generate_rsa_key.py
  tests/unit/util/pseudo/test_pseudonymize.py
Labels: enhancement

#605 add retry mechanism to write_backlog
  CHANGELOG.md
  logprep/abc/output.py
  logprep/connector/elasticsearch/output.py
  logprep/connector/opensearch/output.py
  tests/unit/connector/test_elasticsearch_output.py
  tests/unit/connector/test_opensearch_output.py
Labels: enhancement

#613 configuration overwrites with default values
  CHANGELOG.md
  logprep/util/configuration.py
  tests/unit/util/test_configuration.py
Labels: bug

#400 remove normalizer processor
  CHANGELOG.md
  doc/source/user_manual/configuration/processor.rst
  logprep/connector/file/input.py
  logprep/processor/normalizer/__init__.py
  logprep/processor/normalizer/processor.py
  logprep/processor/normalizer/rule.py
  logprep/registry.py
  pyproject.toml
  quickstart/docker-compose.yml
  quickstart/exampledata/config/pipeline.yml
  quickstart/exampledata/rules/dissector/generic/example_rule.yml
  quickstart/exampledata/rules/dissector/specific/example_rule.yml
  quickstart/exampledata/rules/normalizer/additional_grok_patterns/pattern_file_one
  quickstart/exampledata/rules/normalizer/additional_grok_patterns/pattern_file_two
  quickstart/exampledata/rules/normalizer/generic/example_rule.yml
  quickstart/exampledata/rules/normalizer/normalizer_regex_mapping.yml
  quickstart/exampledata/rules/normalizer/specific/example_rule.yml
  tests/testdata/auto_tests/normalizer/regex_mapping.yml
  tests/testdata/auto_tests/normalizer/rules/generic/auto_test_normalizer_match.json
  tests/testdata/auto_tests/normalizer/rules/generic/auto_test_normalizer_match_test.json
  tests/testdata/auto_tests/normalizer/rules/specific/auto_test_normalizer_mismatch.json
  tests/testdata/auto_tests/normalizer/rules/specific/auto_test_normalizer_mismatch_test.json
  tests/testdata/auto_tests/normalizer/rules/specific/auto_test_normalizer_no_test_.json
  tests/testdata/unit/normalizer/additional_grok_patterns/pattern_file_one
  tests/testdata/unit/normalizer/additional_grok_patterns/pattern_file_two
  tests/testdata/unit/normalizer/additional_grok_patterns/pattern_timestamp
  tests/testdata/unit/normalizer/html_replace_fields.yml
  tests/testdata/unit/normalizer/normalizer_regex_mapping.yml
  tests/testdata/unit/normalizer/regex_mapping.yml
  tests/testdata/unit/normalizer/rules/generic/event_data_test1_NOT_1111_to_test_normalized_test1.json
  tests/testdata/unit/normalizer/rules/generic/event_data_test1_to_test_normalized_something.json
  tests/testdata/unit/normalizer/rules/generic/event_data_test_normalize_to_test_normalized_something.json
  tests/testdata/unit/normalizer/rules/generic/this_is_not_a_rule.not_json
  tests/testdata/unit/normalizer/rules/specific/Test1_id_1111.json
  tests/testdata/unit/normalizer/rules/specific/Test2_id_2222.json
  tests/testdata/unit/normalizer/rules/specific/this_is_not_a_rule.not_json
  tests/unit/processor/grokker/test_grokker.py
  tests/unit/processor/normalizer/__init__.py
  tests/unit/processor/normalizer/test_normalizer.py
  tests/unit/processor/normalizer/test_normalizer_rule.py
  tests/unit/test_configuration.py
  tests/unit/util/test_helper.py
Labels: refactoring

#618 improve `timestamper` processor documentation
  CHANGELOG.md
  logprep/processor/timestamper/processor.py
  logprep/processor/timestamper/rule.py
  tests/unit/processor/timestamper/test_timestamper.py
Labels: enhancement

#617 Pseudonymizer late error on non existing regexmapping
  CHANGELOG.md
  logprep/processor/pseudonymizer/processor.py
  tests/unit/processor/pseudonymizer/test_pseudonymizer.py
Labels: bug

#606 add helm chart
  .github/workflows/ci.yml
  .github/workflows/testing.yml
  .gitignore
  CHANGELOG.md
  Dockerfile
  charts/logprep/.helmignore
  charts/logprep/Chart.yaml
  charts/logprep/templates/_helpers.tpl
  charts/logprep/templates/artifacts.yaml
  charts/logprep/templates/configurations.yaml
  charts/logprep/templates/deployment.yaml
  charts/logprep/templates/exporter-config.yaml
  charts/logprep/templates/exporter-service.yaml
  charts/logprep/templates/http-input-service.yaml
  charts/logprep/templates/input-config.yaml
  charts/logprep/templates/logger-config.yaml
  charts/logprep/templates/output-config.yaml
  charts/logprep/templates/podmonitor.yaml
  charts/logprep/values.yaml
  doc/source/examples/compose.rst
  doc/source/examples/index.rst
  doc/source/examples/minikube.rst
  doc/source/index.rst
  doc/source/installation.rst
  logprep/processor/domain_resolver/processor.py
  logprep/util/event.py
  quickstart/exampledata/config/pipeline.yml
  tests/unit/charts/__init__.py
  tests/unit/charts/test_base.py
  tests/unit/charts/test_deployment.py
  tests/unit/charts/test_exporter_config.py
  tests/unit/charts/test_input_config.py
  tests/unit/charts/test_logger_config.py
  tests/unit/charts/test_output_config.py
  tests/unit/util/test_event.py
Labels: enhancement
