Repository fkie-cad/Logprep, pull requests merged in 2024-11, with the labels that each got.

#703 fix pseudonymizer cache metrics
  CHANGELOG.md
  logprep/processor/pseudonymizer/processor.py
  tests/unit/processor/pseudonymizer/test_pseudonymizer.py
Labels: bug

#704 speed up kafka output tests
  tests/unit/connector/test_confluent_kafka_output.py
Labels: refactoring

#696 update add_field_to function for improved error handling
  CHANGELOG.md
  logprep/abc/input.py
  logprep/abc/processor.py
  logprep/metrics/metrics.py
  logprep/processor/base/exceptions.py
  logprep/processor/clusterer/processor.py
  logprep/processor/dissector/processor.py
  logprep/processor/domain_label_extractor/processor.py
  logprep/processor/domain_resolver/processor.py
  logprep/processor/field_manager/processor.py
  logprep/processor/generic_adder/processor.py
  logprep/processor/generic_resolver/processor.py
  logprep/processor/geoip_enricher/processor.py
  logprep/processor/grokker/processor.py
  logprep/processor/hyperscan_resolver/processor.py
  logprep/processor/labeler/processor.py
  logprep/processor/labeler/rule.py
  logprep/processor/list_comparison/processor.py
  logprep/processor/pre_detector/processor.py
  logprep/processor/pseudonymizer/processor.py
  logprep/processor/requester/processor.py
  logprep/processor/selective_extractor/processor.py
  logprep/processor/string_splitter/processor.py
  logprep/processor/string_splitter/rule.py
  logprep/processor/template_replacer/processor.py
  logprep/util/helper.py
  tests/testdata/auto_tests/clusterer/rules/generic/rule_with_custom_tests.yml
  tests/testdata/auto_tests/clusterer/rules/specific/rule_with_custom_tests.yml
  tests/testdata/auto_tests/dissector/rules/specific/auto_test_mismatch.json
  tests/testdata/auto_tests/dissector/rules/specific/auto_test_no_test_.json
  tests/testdata/auto_tests/dropper/rules/generic/drop_field.json
  tests/testdata/auto_tests/dropper/rules/specific/drop_field.json
  tests/testdata/auto_tests/labeler/rules/generic/auto_test_labeling_match.json
  tests/testdata/auto_tests/labeler/rules/generic/auto_test_labeling_match_existing.json
  tests/testdata/auto_tests/pre_detector/rules/specific/auto_test_pre_detector_mismatch.json
  tests/testdata/auto_tests/pre_detector/rules/specific/auto_test_pre_detector_no_test_.json
  tests/testdata/auto_tests/template_replacer/rules/generic/template_replacer.json
  tests/testdata/auto_tests/template_replacer/rules/specific/template_replacer.json
  tests/unit/connector/base.py
  tests/unit/processor/labeler/test_labeler.py
  tests/unit/processor/requester/test_requester.py
  tests/unit/processor/string_splitter/test_string_splitter.py
  tests/unit/processor/test_process.py
  tests/unit/util/test_auto_rule_tester.py
  tests/unit/util/test_helper_add_field.py
Labels: enhancement

#702 fix requester documentation
  CHANGELOG.md
  logprep/processor/requester/rule.py
  tests/unit/processor/requester/test_requester_rule.py
Labels: bug

#707 add pre-commit hooks and update documentation
  .pre-commit-config.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  pyproject.toml
Labels: enhancement
