Repository fkie-cad/Logprep, pull requests merged in 2025-08, with the labels that each got.

#869 update notebooks
  doc/source/development/notebooks/new_architecture_examples/10_pipeline.ipynb
  doc/source/development/notebooks/new_architecture_examples/8_processors.ipynb
  doc/source/development/notebooks/new_architecture_examples/9_confluentkafka_input.ipynb
  doc/source/development/notebooks/processor_examples/field_manager.ipynb
  doc/source/development/notebooks/pseudonymization/pseudo_tools.ipynb
Labels: enhancement

#867 fix crash on TimeParserException during preprocessing caused by inval…
  logprep/ng/abc/input.py
  logprep/ng/connector/confluent_kafka/input.py
  tests/unit/ng/connector/base.py
  tests/unit/ng/connector/test_confluent_kafka_input.py
  tests/unit/ng/connector/test_console_output.py
  tests/unit/ng/connector/test_dummy_output.py
  tests/unit/ng/connector/test_file_input_default_config.py
  tests/unit/ng/connector/test_http_input.py
  tests/unit/ng/connector/test_json_input.py
  tests/unit/ng/connector/test_jsonl_output.py
  tests/unit/ng/connector/test_opensearch_output.py
  tests/unit/ng/event/test_event.py
  tests/unit/ng/processor/calculator/test_calculator.py
  tests/unit/ng/processor/clusterer/test_clusterer.py
  tests/unit/ng/processor/concatenator/test_concatenator.py
  tests/unit/ng/processor/field_manager/test_field_manager.py
  tests/unit/ng/processor/generic_adder/test_generic_adder.py
  tests/unit/ng/processor/generic_resolver/test_generic_resolver.py
  tests/unit/ng/processor/geoip_enricher/test_geoip_enricher.py
  tests/unit/ng/processor/grokker/test_grokker.py
  tests/unit/ng/processor/key_checker/test_key_checker.py
  tests/unit/ng/processor/pseudonymizer/test_pseudonymizer.py
  tests/unit/ng/processor/requester/test_requester.py
  tests/unit/ng/processor/string_splitter/test_string_splitter.py
  tests/unit/ng/processor/timestamp_differ/test_timestamp_differ.py
  tests/unit/ng/processor/timestamper/test_timestamper.py
  tests/unit/ng/test_pipeline.py
Labels: bug, enhancement

#872 fix ci pipeline
  pyproject.toml
Labels: bug

#870 revise security notes
  doc/source/development/coding_examples.rst
  doc/source/development/notebooks/new_architecture_examples/5_event_backlog.ipynb
  logprep/connector/confluent_kafka/input.py
  logprep/connector/confluent_kafka/output.py
  logprep/connector/dummy/output.py
  logprep/processor/domain_resolver/processor.py
  logprep/processor/generic_adder/rule.py
  logprep/processor/generic_resolver/processor.py
  logprep/processor/generic_resolver/rule.py
  logprep/processor/geoip_enricher/processor.py
  logprep/processor/grokker/processor.py
  logprep/processor/grokker/rule.py
  logprep/processor/labeler/processor.py
  logprep/processor/list_comparison/rule.py
  logprep/processor/pre_detector/processor.py
  logprep/processor/pseudonymizer/processor.py
  logprep/processor/template_replacer/processor.py
  logprep/util/configuration.py
  pyproject.toml
Labels: documentation

#873 update CHANGELOG.md for release v17.0.2
  CHANGELOG.md
Labels: documentation

#875 reintegrate events
  logprep/abc/event.py
  logprep/event/__init__.py
  logprep/event/error_event.py
  logprep/event/event_state.py
  logprep/event/filtered_event.py
  logprep/event/log_event.py
  logprep/event/pseudonym_event.py
  logprep/event/set_event_backlog.py
  logprep/event/sre_event.py
  tests/unit/event/__init__.py
  tests/unit/event/test_error_event.py
  tests/unit/event/test_event.py
  tests/unit/event/test_event_state.py
  tests/unit/event/test_filtered_event.py
  tests/unit/event/test_log_event.py
  tests/unit/event/test_pseudonym_event.py
  tests/unit/event/test_set_event_backlog.py
  tests/unit/event/test_sre_event.py
Labels: refactoring

#865 implement simple sender class
  CHANGELOG.md
  doc/source/development/notebooks/new_architecture_examples/12_sender.ipynb
  logprep/ng/abc/input.py
  logprep/ng/abc/output.py
  logprep/ng/abc/processor.py
  logprep/ng/event/error_event.py
  logprep/ng/event/set_event_backlog.py
  logprep/ng/sender.py
  tests/unit/ng/event/test_error_event.py
  tests/unit/ng/test_sender.py
Labels: enhancement
