Repository fkie-cad/Logprep, pull requests merged in 2025-07, with the labels that each got.

#834 Dev cleanup
  logprep/ng/abc/event.py
  logprep/ng/abc/event_metadata.py
  logprep/ng/connector/__init__.py
  logprep/ng/connector/confluent_kafka/__init__.py
  logprep/ng/connector/confluent_kafka/metadata.py
  logprep/ng/event/__init__.py
  logprep/ng/event/error_event.py
  logprep/ng/event/event_state.py
  logprep/ng/event/log_event.py
  logprep/ng/event/pseudonym_event.py
  logprep/ng/event/sre_event.py
  tests/unit/ng/connector/__init__.py
  tests/unit/ng/connector/confluent_kafka/__init__.py
  tests/unit/ng/connector/confluent_kafka/test_metadata.py
  tests/unit/ng/event/test_error_event.py
  tests/unit/ng/event/test_log_event.py
  tests/unit/ng/event/test_pseudonym_event.py
  tests/unit/ng/event/test_sre_event.py
  tests/unit/ng/test_event.py
  tests/unit/ng/test_event_state.py
Labels: refactoring

#833 use new logevent class instead of plain dict
  CHANGELOG.md
  logprep/ng/abc/processor.py
  logprep/ng/processor/field_manager/processor.py
  tests/unit/ng/processor/base.py
  tests/unit/ng/processor/field_manager/test_field_manager.py
Labels: enhancement

#837 make amides use new logevent class
  .vscode/settings.json
  logprep/ng/abc/processor.py
  logprep/ng/processor/amides/__init__.py
  logprep/ng/processor/amides/processor.py
  logprep/registry.py
  pyproject.toml
  tests/unit/ng/processor/amides/__init__.py
  tests/unit/ng/processor/amides/test_amides.py
  tests/unit/ng/processor/base.py
Labels: enhancement

#838 make calculator use new logevent
  logprep/ng/processor/calculator/__init__.py
  logprep/ng/processor/calculator/processor.py
  logprep/registry.py
  tests/unit/ng/processor/calculator/__init__.py
  tests/unit/ng/processor/calculator/test_calculator.py
  tests/unit/ng/processor/field_manager/test_field_manager_rule.py
Labels: enhancement

#840 Dev use logevent class in clusterer
  .vscode/settings.json
  logprep/ng/processor/clusterer/__init__.py
  logprep/ng/processor/clusterer/processor.py
  logprep/registry.py
  tests/unit/ng/processor/clusterer/__init__.py
  tests/unit/ng/processor/clusterer/test_clusterer.py
Labels: enhancement

#845 event backlog implementation
  logprep/ng/abc/event.py
  logprep/ng/event/set_event_backlog.py
  tests/unit/ng/event/test_set_event_backlog.py
Labels: enhancement

#843 make predetector use new logevents
  logprep/ng/event/log_event.py
  logprep/ng/event/sre_event.py
  logprep/ng/processor/pre_detector/__init__.py
  logprep/ng/processor/pre_detector/processor.py
  logprep/registry.py
  tests/unit/ng/event/test_sre_event.py
  tests/unit/ng/processor/pre_detector/__init__.py
  tests/unit/ng/processor/pre_detector/test_pre_detector.py
Labels: enhancement

#849 use logevent selective_extractor
  logprep/ng/event/filtered_event.py
  logprep/ng/processor/selective_extractor/__init__.py
  logprep/ng/processor/selective_extractor/processor.py
  logprep/registry.py
  tests/unit/ng/event/test_filtered_event.py
  tests/unit/ng/processor/selective_extractor/__init__.py
  tests/unit/ng/processor/selective_extractor/test_selective_extractor.py
Labels: enhancement

#858 Review sprint52
  doc/source/development/notebooks/new_architecture_examples/1_event_metadata.ipynb
  doc/source/development/notebooks/new_architecture_examples/2_event_state.ipynb
  doc/source/development/notebooks/new_architecture_examples/3_event_class.ipynb
  doc/source/development/notebooks/new_architecture_examples/4_further_event_classes.ipynb
  doc/source/development/notebooks/new_architecture_examples/5_event_backlog.ipynb
  tests/unit/ng/connector/confluent_kafka/test_metadata.py
Labels: documentation, enhancement

#853 dev input connector iterator
  .gitignore
  logprep/ng/abc/input.py
  logprep/ng/connector/confluent_kafka/input.py
  logprep/ng/connector/dummy/__init__.py
  logprep/ng/connector/dummy/input.py
  logprep/ng/connector/file/__init__.py
  logprep/ng/connector/file/input.py
  logprep/ng/connector/http/__init__.py
  logprep/ng/connector/http/input.py
  logprep/ng/connector/json/__init__.py
  logprep/ng/connector/json/input.py
  logprep/ng/processor/domain_resolver/processor.py
  logprep/ng/processor/replacer/processor.py
  logprep/registry.py
  logprep/util/http.py
  pyproject.toml
  tests/unit/connector/test_confluent_kafka_common.py
  tests/unit/ng/connector/base.py
  tests/unit/ng/connector/test_confluent_kafka_input.py
  tests/unit/ng/connector/test_confluent_kafka_metadata.py
  tests/unit/ng/connector/test_dummy_input.py
  tests/unit/ng/connector/test_file_input_default_config.py
  tests/unit/ng/connector/test_http_input.py
  tests/unit/ng/connector/test_json_input.py
Labels: enhancement

#859 Dev opensearch output stores event object
  .vscode/settings.json
  CHANGELOG.md
  doc/source/development/notebooks/new_architecture_examples/4_further_event_classes.ipynb
  doc/source/development/notebooks/new_architecture_examples/6_opensearch_output.ipynb
  logprep/ng/connector/opensearch/__init__.py
  logprep/ng/connector/opensearch/output.py
  logprep/registry.py
  tests/unit/ng/connector/test_opensearch_output.py
Labels: enhancement

#860 setup event backlog in abstract input class and event registration an…
  CHANGELOG.md
  doc/source/development/notebooks/new_architecture_examples/1_event_metadata.ipynb
  logprep/abc/component.py
  logprep/ng/abc/input.py
  logprep/ng/connector/confluent_kafka/input.py
  logprep/ng/connector/confluent_kafka/metadata.py
  logprep/ng/connector/dummy/input.py
  logprep/ng/connector/file/input.py
  logprep/ng/connector/http/input.py
  logprep/ng/connector/json/input.py
  tests/unit/component/base.py
  tests/unit/connector/test_confluent_kafka_common.py
  tests/unit/connector/test_confluent_kafka_input.py
  tests/unit/ng/connector/base.py
  tests/unit/ng/connector/test_confluent_kafka_input.py
  tests/unit/ng/connector/test_confluent_kafka_metadata.py
  tests/unit/ng/connector/test_dummy_input.py
  tests/unit/ng/connector/test_dummy_output.py
  tests/unit/ng/connector/test_file_input_default_config.py
  tests/unit/ng/connector/test_http_input.py
  tests/unit/ng/connector/test_json_input.py
  tests/unit/ng/processor/pre_detector/test_pre_detector.py
Labels: enhancement
