Repository fkie-cad/Logprep, pull requests merged in 2025-03, with the labels that each got.

#776 fix acceptance tests
  pyproject.toml
  tests/acceptance/test_config_refresh.py
  tests/acceptance/test_error_output.py
  tests/acceptance/test_file_input.py
  tests/acceptance/test_full_configuration.py
  tests/acceptance/test_http_input_with_requests.py
  tests/acceptance/test_multiple_outputs.py
  tests/acceptance/test_wineventlog_pseudonymization.py
  tests/acceptance/util.py
Labels: bug

#775 fix typing in exporter
  logprep/metrics/exporter.py
Labels: refactoring

#781 fix broken configuration test
  tests/unit/util/test_configuration.py
Labels: bug

#785 fix log arrival timestamp
  CHANGELOG.md
  logprep/abc/input.py
  tests/unit/connector/base.py
Labels: bug

#770 add ability to write the full event to one singular target field
  CHANGELOG.md
  logprep/abc/connector.py
  logprep/abc/input.py
  logprep/connector/http/input.py
  logprep/util/helper.py
  tests/unit/connector/base.py
  tests/unit/connector/test_http_input.py
Labels: enhancement
